[package]
name = "mbox"
version = "0.1.1"
authors = ["kennytm <kennytm@gmail.com>"]
license = "MIT"
keywords = ["malloc", "free", "ffi", "box", "cstr"]
repository = "https://github.com/kennytm/mbox"
readme = "README.md"
description = """malloc-based box.

Supports wrapping pointers or null-terminated strings returned from malloc as a Rust type, which
will be free'd on drop.
"""

build = "build.rs"
exclude = [".travis.yml", "appveyor.yml", "appveyor.bat", ".gitignore", ".gitattributes"]

[dependencies]
libc = "0.2.13"

[build-dependencies]
rustc_version = "0.1.7"
semver = "0.1.20" # rustc_version doesn't use the latest semver (0.2.3) ಠ_ಠ

[features]
no-std = []

